### ISSUE TITLE
Deprecated call in Web::Request

### ISSUE THREAD

**Issue by lancew** [supernovus/perl6-web#2]
Saw 1 call to deprecated code during execution.
================================================================================
%new = itemized hash called at:
  lib/Web/Request.pm6, line 33
Deprecated since v2014.7, will be removed with release v2015.7!
Please use %new = %(itemized hash) instead.
--------------------------------------------------------------------------------
Please contact the author to have these calls to deprecated code adapted,
so that this message will disappear!

Please note that *ALL* deprecated features will be removed at the release
of Perl 6.0.0 (expected sometime in 2015).

**Comment by supernovus** [comment]
This has been resolved for ages.
